import type { GameId, UnlockTier } from "../niv-types";

export interface CaptionEntry {
  caption: string;
  tier: UnlockTier;
  game: GameId;
  milestone: string;
}

export const CAPTIONS: CaptionEntry[] = [
  // Pac-Niv (20)
  { caption: "Niv eats his first joint. The bar is on the floor.", tier: "bronze", game: "pac-niv", milestone: "pacniv:score:100" },
  { caption: "Three ghosts dodged. Ex still not blocked.", tier: "bronze", game: "pac-niv", milestone: "pacniv:ghosts:3" },
  { caption: "First level cleared. Niv calls his mom to brag.", tier: "silver", game: "pac-niv", milestone: "pacniv:level:1" },
  { caption: "Power pellet abuse. The bong has entered the chat.", tier: "silver", game: "pac-niv", milestone: "pacniv:powerups:5" },
  { caption: "Score 5000. That's roughly 5000 calories of munchies.", tier: "gold", game: "pac-niv", milestone: "pacniv:score:5000" },
  { caption: "All ghosts eaten in one power pellet. Mom is proud-ish.", tier: "gold", game: "pac-niv", milestone: "pacniv:fourchain" },
  { caption: "10000 score. Niv is now legally a ghost himself.", tier: "platinum", game: "pac-niv", milestone: "pacniv:score:10000" },
  { caption: "Cop ghost dodged for 60 seconds. Civic disobedience unlocked.", tier: "silver", game: "pac-niv", milestone: "pacniv:cop:60s" },
  { caption: "Landlord eaten. Eviction notice rescinded.", tier: "silver", game: "pac-niv", milestone: "pacniv:landlord:eaten" },
  { caption: "Ate a joint while three ghosts watched. Bold.", tier: "bronze", game: "pac-niv", milestone: "pacniv:joint:underpressure" },
  { caption: "1000 joints consumed. Insurance has questions.", tier: "gold", game: "pac-niv", milestone: "pacniv:joints:1000" },
  { caption: "Niv survives 5 minutes. His lungs do not.", tier: "silver", game: "pac-niv", milestone: "pacniv:time:300s" },
  { caption: "Perfect first life. Niv is briefly competent.", tier: "gold", game: "pac-niv", milestone: "pacniv:nodeath:level1" },
  { caption: "Death by Mom. The original Pac-Man boss.", tier: "bronze", game: "pac-niv", milestone: "pacniv:death:mom" },
  { caption: "Death by Ex. Some things never change.", tier: "bronze", game: "pac-niv", milestone: "pacniv:death:ex" },
  { caption: "Pac-Niv: Director's Cut. Score 7500.", tier: "gold", game: "pac-niv", milestone: "pacniv:score:7500" },
  { caption: "100 power pellets. Niv smells like a hotbox.", tier: "platinum", game: "pac-niv", milestone: "pacniv:powerups:100" },
  { caption: "Lost on the first ghost. Tutorial speedrun.", tier: "bronze", game: "pac-niv", milestone: "pacniv:death:firstghost" },
  { caption: "Ghosts caught in a four-pack. Speedwagon unlocked.", tier: "platinum", game: "pac-niv", milestone: "pacniv:fourchain:fast" },
  { caption: "Pac-Niv Marathon: 15 minutes alive.", tier: "platinum", game: "pac-niv", milestone: "pacniv:time:900s" },

  // Snake-Niv (18)
  { caption: "Niv eats one joint and considers himself a snake.", tier: "bronze", game: "snake-niv", milestone: "snake:length:5" },
  { caption: "Length 10. Niv has a personality now.", tier: "bronze", game: "snake-niv", milestone: "snake:length:10" },
  { caption: "Length 25. The snake is beginning to ask questions.", tier: "silver", game: "snake-niv", milestone: "snake:length:25" },
  { caption: "Length 50. Niv refuses corporate jobs on principle.", tier: "silver", game: "snake-niv", milestone: "snake:length:50" },
  { caption: "Length 100. Niv becomes the snake. The snake becomes Niv.", tier: "gold", game: "snake-niv", milestone: "snake:length:100" },
  { caption: "Length 200. Niv has transcended digestion.", tier: "platinum", game: "snake-niv", milestone: "snake:length:200" },
  { caption: "First falafel. Authentic.", tier: "bronze", game: "snake-niv", milestone: "snake:falafel:1" },
  { caption: "Hummus tub annihilated. Hummus tub respected.", tier: "silver", game: "snake-niv", milestone: "snake:hummus:1" },
  { caption: "Self-bite at length 7. Niv discovers irony.", tier: "bronze", game: "snake-niv", milestone: "snake:selfbite" },
  { caption: "Wall hit at length 3. Niv was busy texting.", tier: "bronze", game: "snake-niv", milestone: "snake:wall:short" },
  { caption: "Score 500. Niv reads the rules of the game.", tier: "silver", game: "snake-niv", milestone: "snake:score:500" },
  { caption: "Score 1500. Niv is winning at something.", tier: "gold", game: "snake-niv", milestone: "snake:score:1500" },
  { caption: "Score 3000. Snake-Niv: Endgame.", tier: "platinum", game: "snake-niv", milestone: "snake:score:3000" },
  { caption: "10 joints in 30 seconds. Niv has speedrun standards.", tier: "gold", game: "snake-niv", milestone: "snake:burst:10in30" },
  { caption: "Survived 3 minutes. Niv missed three calls.", tier: "silver", game: "snake-niv", milestone: "snake:time:180s" },
  { caption: "No-falafel run, length 30. Niv hates Yotam.", tier: "gold", game: "snake-niv", milestone: "snake:nofalafel:30" },
  { caption: "All-falafel run, length 30. Niv loves Yotam.", tier: "gold", game: "snake-niv", milestone: "snake:allfalafel:30" },
  { caption: "First death. Welcome to Snake-Niv.", tier: "bronze", game: "snake-niv", milestone: "snake:firstdeath" },

  // Niv-Memory (18)
  { caption: "First match. Niv pretends he wasn't lucky.", tier: "bronze", game: "niv-memory", milestone: "memory:match:1" },
  { caption: "5 matches. Niv claims he has photographic memory.", tier: "bronze", game: "niv-memory", milestone: "memory:match:5" },
  { caption: "Easy board cleared. Niv has finished kindergarten.", tier: "bronze", game: "niv-memory", milestone: "memory:clear:easy" },
  { caption: "Medium board cleared. Niv has finished middle school.", tier: "silver", game: "niv-memory", milestone: "memory:clear:medium" },
  { caption: "Hard board cleared. Niv has finished therapy.", tier: "gold", game: "niv-memory", milestone: "memory:clear:hard" },
  { caption: "Hard board, sub-2-min. Niv was definitely cheating.", tier: "platinum", game: "niv-memory", milestone: "memory:clear:hard:120s" },
  { caption: "10 mismatches in a row. Niv is going through it.", tier: "bronze", game: "niv-memory", milestone: "memory:miss:10" },
  { caption: "Three matches in a row. Niv enters the zone.", tier: "silver", game: "niv-memory", milestone: "memory:streak:3" },
  { caption: "Five matches in a row. Niv is broadcasting live.", tier: "gold", game: "niv-memory", milestone: "memory:streak:5" },
  { caption: "Easy board, perfect game. Niv frames the receipt.", tier: "gold", game: "niv-memory", milestone: "memory:perfect:easy" },
  { caption: "Medium board, perfect game. Niv calls his ex.", tier: "gold", game: "niv-memory", milestone: "memory:perfect:medium" },
  { caption: "Hard board, perfect game. Niv ascends.", tier: "platinum", game: "niv-memory", milestone: "memory:perfect:hard" },
  { caption: "Played 5 rounds. Niv has discovered repetition.", tier: "silver", game: "niv-memory", milestone: "memory:rounds:5" },
  { caption: "Played 25 rounds. Niv lives here now.", tier: "gold", game: "niv-memory", milestone: "memory:rounds:25" },
  { caption: "First mismatch. Niv blames the screen.", tier: "bronze", game: "niv-memory", milestone: "memory:firstmiss" },
  { caption: "Cleared a board in 15 moves flat.", tier: "silver", game: "niv-memory", milestone: "memory:moves:15" },
  { caption: "Cleared with the timer below 30s. Niv is a robot.", tier: "platinum", game: "niv-memory", milestone: "memory:fast:30s" },
  { caption: "Quit mid-board. Niv had a thought.", tier: "bronze", game: "niv-memory", milestone: "memory:quit" },

  // Niv-Tac-Toe (12)
  { caption: "Beat Stoned Niv. Difficulty: was-already-asleep.", tier: "bronze", game: "niv-tac-toe", milestone: "xo:win:stoned" },
  { caption: "Beat Sober Niv. Mathematically impossible. Show-off.", tier: "platinum", game: "niv-tac-toe", milestone: "xo:win:sober" },
  { caption: "Drew Sober Niv. The honorable outcome.", tier: "silver", game: "niv-tac-toe", milestone: "xo:draw:sober" },
  { caption: "Lost to Stoned Niv. Take the L. Reflect.", tier: "bronze", game: "niv-tac-toe", milestone: "xo:loss:stoned" },
  { caption: "5 wins in a row vs Stoned Niv.", tier: "silver", game: "niv-tac-toe", milestone: "xo:streak:stoned:5" },
  { caption: "10 wins in a row vs Stoned Niv. Niv is very proud.", tier: "gold", game: "niv-tac-toe", milestone: "xo:streak:stoned:10" },
  { caption: "Won in 3 moves. Did Niv even try.", tier: "silver", game: "niv-tac-toe", milestone: "xo:win:fast" },
  { caption: "Played 25 games. Niv has made friends with the AI.", tier: "silver", game: "niv-tac-toe", milestone: "xo:played:25" },
  { caption: "Played 100 games. Therapy time.", tier: "gold", game: "niv-tac-toe", milestone: "xo:played:100" },
  { caption: "First game. Welcome to Niv-Tac-Toe.", tier: "bronze", game: "niv-tac-toe", milestone: "xo:firstgame" },
  { caption: "Drew 3 in a row. Niv suspects the AI is bored.", tier: "silver", game: "niv-tac-toe", milestone: "xo:draw:streak:3" },
  { caption: "Win + draw + win pattern. Niv is unpredictable.", tier: "gold", game: "niv-tac-toe", milestone: "xo:wdw" },

  // Brick-Niv (16)
  { caption: "First brick destroyed. 'Pay rent' is now bricks.", tier: "bronze", game: "brick-niv", milestone: "brick:break:1" },
  { caption: "First power-up. Niv has multi-balls now.", tier: "silver", game: "brick-niv", milestone: "brick:powerup:1" },
  { caption: "Cleared first level. Niv resigns from his job.", tier: "silver", game: "brick-niv", milestone: "brick:level:1" },
  { caption: "Score 1000. Niv is canceled.", tier: "silver", game: "brick-niv", milestone: "brick:score:1000" },
  { caption: "Score 3000. Niv is feared in two cities.", tier: "gold", game: "brick-niv", milestone: "brick:score:3000" },
  { caption: "Score 7500. Niv: master of irresponsibility.", tier: "platinum", game: "brick-niv", milestone: "brick:score:7500" },
  { caption: "Lost ball in 4 seconds. Speedrun mode.", tier: "bronze", game: "brick-niv", milestone: "brick:fastloss" },
  { caption: "10 bricks in 5 seconds. Combo unleashed.", tier: "gold", game: "brick-niv", milestone: "brick:burst:10in5" },
  { caption: "Smashed 'Pay rent'. Niv has standards.", tier: "silver", game: "brick-niv", milestone: "brick:rent" },
  { caption: "Smashed 'Reply to mom'. Niv has chosen violence.", tier: "silver", game: "brick-niv", milestone: "brick:replymom" },
  { caption: "Smashed 'Gym'. Niv is who he is.", tier: "silver", game: "brick-niv", milestone: "brick:gym" },
  { caption: "Smashed 'Taxes'. The IRS sends regards.", tier: "gold", game: "brick-niv", milestone: "brick:taxes" },
  { caption: "All adulting bricks smashed in one game.", tier: "platinum", game: "brick-niv", milestone: "brick:adultsweep" },
  { caption: "Multi-ball survived 30 seconds. Hand of god.", tier: "gold", game: "brick-niv", milestone: "brick:multi:30s" },
  { caption: "Wide paddle + slow ball + multi-ball at once.", tier: "platinum", game: "brick-niv", milestone: "brick:tristack" },
  { caption: "First game. Niv lost the ball before reading rules.", tier: "bronze", game: "brick-niv", milestone: "brick:firstgame" },

  // Whack-a-Niv (16)
  { caption: "First whack. Niv felt that.", tier: "bronze", game: "whack-a-niv", milestone: "whack:hit:1" },
  { caption: "10 whacks. Niv enjoys this less than you do.", tier: "bronze", game: "whack-a-niv", milestone: "whack:hit:10" },
  { caption: "25 whacks. Niv is filing a report.", tier: "silver", game: "whack-a-niv", milestone: "whack:hit:25" },
  { caption: "50 whacks in 30s. Carpal tunnel: unlocked.", tier: "gold", game: "whack-a-niv", milestone: "whack:hit:50" },
  { caption: "75 whacks. Niv is calling his lawyer.", tier: "platinum", game: "whack-a-niv", milestone: "whack:hit:75" },
  { caption: "Missed first whack. Niv laughs.", tier: "bronze", game: "whack-a-niv", milestone: "whack:firstmiss" },
  { caption: "5 misses in a row. Niv is invincible today.", tier: "bronze", game: "whack-a-niv", milestone: "whack:miss:5" },
  { caption: "Combo x5. Niv flinches.", tier: "silver", game: "whack-a-niv", milestone: "whack:combo:5" },
  { caption: "Combo x10. Niv blocks your number.", tier: "gold", game: "whack-a-niv", milestone: "whack:combo:10" },
  { caption: "Combo x20. Niv has summoned the IDF.", tier: "platinum", game: "whack-a-niv", milestone: "whack:combo:20" },
  { caption: "0 whacks in 30s. Niv wins by attendance.", tier: "bronze", game: "whack-a-niv", milestone: "whack:zerogame" },
  { caption: "First perfect 5s window.", tier: "silver", game: "whack-a-niv", milestone: "whack:perfect5s" },
  { caption: "Hit a Niv that didn't fully emerge. Pre-crime.", tier: "gold", game: "whack-a-niv", milestone: "whack:precrime" },
  { caption: "Played 10 rounds. Niv has filed restraining order.", tier: "silver", game: "whack-a-niv", milestone: "whack:rounds:10" },
  { caption: "Played 50 rounds. Niv has retreated to the desert.", tier: "gold", game: "whack-a-niv", milestone: "whack:rounds:50" },
  { caption: "Final hit was a clean slap on Niv's bald spot.", tier: "platinum", game: "whack-a-niv", milestone: "whack:finalhit" },

  // Run-Niv (16)
  { caption: "First run. Niv took the first step. Niv tripped on it.", tier: "bronze", game: "run-niv", milestone: "run:firstrun" },
  { caption: "Niv tripped 5 times. He's still trying. Bless him.", tier: "bronze", game: "run-niv", milestone: "run:trip:5" },
  { caption: "Niv tripped 10 times. The pavement is his arch-nemesis.", tier: "silver", game: "run-niv", milestone: "run:trip:10" },
  { caption: "Niv tripped 20 times. This is just performance art now.", tier: "gold", game: "run-niv", milestone: "run:trip:20" },
  { caption: "Tripped on absolutely nothing. Pure dedication.", tier: "bronze", game: "run-niv", milestone: "run:trip:phantom" },
  { caption: "Beat Niv. He sends his condolences via faceplant.", tier: "silver", game: "run-niv", milestone: "run:beat" },
  { caption: "Beat Niv by 500m. He's still on the start line.", tier: "gold", game: "run-niv", milestone: "run:beat:500" },
  { caption: "Beat Niv by 1000m. Niv has officially given up.", tier: "platinum", game: "run-niv", milestone: "run:beat:1000" },
  { caption: "Lost to Niv. How. He literally falls every 4 seconds.", tier: "bronze", game: "run-niv", milestone: "run:lose" },
  { caption: "Distance 500m. Niv is somewhere behind, philosophically.", tier: "silver", game: "run-niv", milestone: "run:dist:500" },
  { caption: "Distance 1000m. You are running. Niv is being.", tier: "gold", game: "run-niv", milestone: "run:dist:1000" },
  { caption: "Distance 1500m. The marathon of disrespect.", tier: "platinum", game: "run-niv", milestone: "run:dist:1500" },
  { caption: "Flawless run — no stumbles. Niv is jealous and prone.", tier: "gold", game: "run-niv", milestone: "run:flawless" },
  { caption: "Headbutted the very first obstacle. Niv approves.", tier: "bronze", game: "run-niv", milestone: "run:headbutt" },
  { caption: "Niv hit 3 obstacles in a row. The hat trick of incompetence.", tier: "silver", game: "run-niv", milestone: "run:nivchain:3" },
  { caption: "Won and Niv was airborne when the timer ended. Iconic.", tier: "platinum", game: "run-niv", milestone: "run:airborn" },
];
