// AUTO-GENERATED by scripts/prep-assets.ts. Do not edit by hand.
import type { NivManifest } from "./niv-types";
export const NIV_MANIFEST: NivManifest = {
  "version": 1,
  "generatedAt": "2026-05-09T19:06:23.239Z",
  "assets": [
    {
      "slug": "cb2aea18265e",
      "caption": "Niv eats his first joint. The bar is on the floor.",
      "tier": "bronze",
      "game": "pac-niv",
      "milestone": "pacniv:score:100",
      "paths": {
        "avatar64": "/niv/cb2aea18265e/avatar-64.webp",
        "avatar128": "/niv/cb2aea18265e/avatar-128.webp",
        "avatar256": "/niv/cb2aea18265e/avatar-256.webp",
        "portrait720": "/niv/cb2aea18265e/portrait-720.webp"
      }
    },
    {
      "slug": "db156123435a",
      "caption": "Three ghosts dodged. Ex still not blocked.",
      "tier": "bronze",
      "game": "pac-niv",
      "milestone": "pacniv:ghosts:3",
      "paths": {
        "avatar64": "/niv/db156123435a/avatar-64.webp",
        "avatar128": "/niv/db156123435a/avatar-128.webp",
        "avatar256": "/niv/db156123435a/avatar-256.webp",
        "portrait720": "/niv/db156123435a/portrait-720.webp"
      }
    },
    {
      "slug": "4f19744c47b2",
      "caption": "First level cleared. Niv calls his mom to brag.",
      "tier": "silver",
      "game": "pac-niv",
      "milestone": "pacniv:level:1",
      "paths": {
        "avatar64": "/niv/4f19744c47b2/avatar-64.webp",
        "avatar128": "/niv/4f19744c47b2/avatar-128.webp",
        "avatar256": "/niv/4f19744c47b2/avatar-256.webp",
        "portrait720": "/niv/4f19744c47b2/portrait-720.webp"
      }
    },
    {
      "slug": "70968ca02637",
      "caption": "Power pellet abuse. The bong has entered the chat.",
      "tier": "silver",
      "game": "pac-niv",
      "milestone": "pacniv:powerups:5",
      "paths": {
        "avatar64": "/niv/70968ca02637/avatar-64.webp",
        "avatar128": "/niv/70968ca02637/avatar-128.webp",
        "avatar256": "/niv/70968ca02637/avatar-256.webp",
        "portrait720": "/niv/70968ca02637/portrait-720.webp"
      }
    },
    {
      "slug": "d05893d83c5e",
      "caption": "Score 5000. That's roughly 5000 calories of munchies.",
      "tier": "gold",
      "game": "pac-niv",
      "milestone": "pacniv:score:5000",
      "paths": {
        "avatar64": "/niv/d05893d83c5e/avatar-64.webp",
        "avatar128": "/niv/d05893d83c5e/avatar-128.webp",
        "avatar256": "/niv/d05893d83c5e/avatar-256.webp",
        "portrait720": "/niv/d05893d83c5e/portrait-720.webp"
      }
    },
    {
      "slug": "2276396101bb",
      "caption": "All ghosts eaten in one power pellet. Mom is proud-ish.",
      "tier": "gold",
      "game": "pac-niv",
      "milestone": "pacniv:fourchain",
      "paths": {
        "avatar64": "/niv/2276396101bb/avatar-64.webp",
        "avatar128": "/niv/2276396101bb/avatar-128.webp",
        "avatar256": "/niv/2276396101bb/avatar-256.webp",
        "portrait720": "/niv/2276396101bb/portrait-720.webp"
      }
    },
    {
      "slug": "7bdb81da8da3",
      "caption": "10000 score. Niv is now legally a ghost himself.",
      "tier": "platinum",
      "game": "pac-niv",
      "milestone": "pacniv:score:10000",
      "paths": {
        "avatar64": "/niv/7bdb81da8da3/avatar-64.webp",
        "avatar128": "/niv/7bdb81da8da3/avatar-128.webp",
        "avatar256": "/niv/7bdb81da8da3/avatar-256.webp",
        "portrait720": "/niv/7bdb81da8da3/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/7bdb81da8da3/stylized-pixel.webp",
          "renaissance": "/niv/7bdb81da8da3/stylized-renaissance.webp",
          "anime": "/niv/7bdb81da8da3/stylized-anime.webp",
          "mugshot": "/niv/7bdb81da8da3/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "c901eb813fbe",
      "caption": "Cop ghost dodged for 60 seconds. Civic disobedience unlocked.",
      "tier": "silver",
      "game": "pac-niv",
      "milestone": "pacniv:cop:60s",
      "paths": {
        "avatar64": "/niv/c901eb813fbe/avatar-64.webp",
        "avatar128": "/niv/c901eb813fbe/avatar-128.webp",
        "avatar256": "/niv/c901eb813fbe/avatar-256.webp",
        "portrait720": "/niv/c901eb813fbe/portrait-720.webp"
      }
    },
    {
      "slug": "97fe82fd5fd5",
      "caption": "Landlord eaten. Eviction notice rescinded.",
      "tier": "silver",
      "game": "pac-niv",
      "milestone": "pacniv:landlord:eaten",
      "paths": {
        "avatar64": "/niv/97fe82fd5fd5/avatar-64.webp",
        "avatar128": "/niv/97fe82fd5fd5/avatar-128.webp",
        "avatar256": "/niv/97fe82fd5fd5/avatar-256.webp",
        "portrait720": "/niv/97fe82fd5fd5/portrait-720.webp"
      }
    },
    {
      "slug": "cc4c8021a4c0",
      "caption": "Ate a joint while three ghosts watched. Bold.",
      "tier": "bronze",
      "game": "pac-niv",
      "milestone": "pacniv:joint:underpressure",
      "paths": {
        "avatar64": "/niv/cc4c8021a4c0/avatar-64.webp",
        "avatar128": "/niv/cc4c8021a4c0/avatar-128.webp",
        "avatar256": "/niv/cc4c8021a4c0/avatar-256.webp",
        "portrait720": "/niv/cc4c8021a4c0/portrait-720.webp"
      }
    },
    {
      "slug": "b21b74277385",
      "caption": "1000 joints consumed. Insurance has questions.",
      "tier": "gold",
      "game": "pac-niv",
      "milestone": "pacniv:joints:1000",
      "paths": {
        "avatar64": "/niv/b21b74277385/avatar-64.webp",
        "avatar128": "/niv/b21b74277385/avatar-128.webp",
        "avatar256": "/niv/b21b74277385/avatar-256.webp",
        "portrait720": "/niv/b21b74277385/portrait-720.webp"
      }
    },
    {
      "slug": "3fd956c34722",
      "caption": "Niv survives 5 minutes. His lungs do not.",
      "tier": "silver",
      "game": "pac-niv",
      "milestone": "pacniv:time:300s",
      "paths": {
        "avatar64": "/niv/3fd956c34722/avatar-64.webp",
        "avatar128": "/niv/3fd956c34722/avatar-128.webp",
        "avatar256": "/niv/3fd956c34722/avatar-256.webp",
        "portrait720": "/niv/3fd956c34722/portrait-720.webp"
      }
    },
    {
      "slug": "dc8599ea31dd",
      "caption": "Perfect first life. Niv is briefly competent.",
      "tier": "gold",
      "game": "pac-niv",
      "milestone": "pacniv:nodeath:level1",
      "paths": {
        "avatar64": "/niv/dc8599ea31dd/avatar-64.webp",
        "avatar128": "/niv/dc8599ea31dd/avatar-128.webp",
        "avatar256": "/niv/dc8599ea31dd/avatar-256.webp",
        "portrait720": "/niv/dc8599ea31dd/portrait-720.webp"
      }
    },
    {
      "slug": "0fd639be0b75",
      "caption": "Death by Mom. The original Pac-Man boss.",
      "tier": "bronze",
      "game": "pac-niv",
      "milestone": "pacniv:death:mom",
      "paths": {
        "avatar64": "/niv/0fd639be0b75/avatar-64.webp",
        "avatar128": "/niv/0fd639be0b75/avatar-128.webp",
        "avatar256": "/niv/0fd639be0b75/avatar-256.webp",
        "portrait720": "/niv/0fd639be0b75/portrait-720.webp"
      }
    },
    {
      "slug": "a6cf8f5661aa",
      "caption": "Death by Ex. Some things never change.",
      "tier": "bronze",
      "game": "pac-niv",
      "milestone": "pacniv:death:ex",
      "paths": {
        "avatar64": "/niv/a6cf8f5661aa/avatar-64.webp",
        "avatar128": "/niv/a6cf8f5661aa/avatar-128.webp",
        "avatar256": "/niv/a6cf8f5661aa/avatar-256.webp",
        "portrait720": "/niv/a6cf8f5661aa/portrait-720.webp"
      }
    },
    {
      "slug": "63c93c70ce60",
      "caption": "Pac-Niv: Director's Cut. Score 7500.",
      "tier": "gold",
      "game": "pac-niv",
      "milestone": "pacniv:score:7500",
      "paths": {
        "avatar64": "/niv/63c93c70ce60/avatar-64.webp",
        "avatar128": "/niv/63c93c70ce60/avatar-128.webp",
        "avatar256": "/niv/63c93c70ce60/avatar-256.webp",
        "portrait720": "/niv/63c93c70ce60/portrait-720.webp"
      }
    },
    {
      "slug": "292f5384cdf9",
      "caption": "100 power pellets. Niv smells like a hotbox.",
      "tier": "platinum",
      "game": "pac-niv",
      "milestone": "pacniv:powerups:100",
      "paths": {
        "avatar64": "/niv/292f5384cdf9/avatar-64.webp",
        "avatar128": "/niv/292f5384cdf9/avatar-128.webp",
        "avatar256": "/niv/292f5384cdf9/avatar-256.webp",
        "portrait720": "/niv/292f5384cdf9/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/292f5384cdf9/stylized-pixel.webp",
          "renaissance": "/niv/292f5384cdf9/stylized-renaissance.webp",
          "anime": "/niv/292f5384cdf9/stylized-anime.webp",
          "mugshot": "/niv/292f5384cdf9/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "5336bb785d2e",
      "caption": "Lost on the first ghost. Tutorial speedrun.",
      "tier": "bronze",
      "game": "pac-niv",
      "milestone": "pacniv:death:firstghost",
      "paths": {
        "avatar64": "/niv/5336bb785d2e/avatar-64.webp",
        "avatar128": "/niv/5336bb785d2e/avatar-128.webp",
        "avatar256": "/niv/5336bb785d2e/avatar-256.webp",
        "portrait720": "/niv/5336bb785d2e/portrait-720.webp"
      }
    },
    {
      "slug": "f61719ce8d3f",
      "caption": "Ghosts caught in a four-pack. Speedwagon unlocked.",
      "tier": "platinum",
      "game": "pac-niv",
      "milestone": "pacniv:fourchain:fast",
      "paths": {
        "avatar64": "/niv/f61719ce8d3f/avatar-64.webp",
        "avatar128": "/niv/f61719ce8d3f/avatar-128.webp",
        "avatar256": "/niv/f61719ce8d3f/avatar-256.webp",
        "portrait720": "/niv/f61719ce8d3f/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/f61719ce8d3f/stylized-pixel.webp",
          "renaissance": "/niv/f61719ce8d3f/stylized-renaissance.webp",
          "anime": "/niv/f61719ce8d3f/stylized-anime.webp",
          "mugshot": "/niv/f61719ce8d3f/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "f066823c31c2",
      "caption": "Pac-Niv Marathon: 15 minutes alive.",
      "tier": "platinum",
      "game": "pac-niv",
      "milestone": "pacniv:time:900s",
      "paths": {
        "avatar64": "/niv/f066823c31c2/avatar-64.webp",
        "avatar128": "/niv/f066823c31c2/avatar-128.webp",
        "avatar256": "/niv/f066823c31c2/avatar-256.webp",
        "portrait720": "/niv/f066823c31c2/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/f066823c31c2/stylized-pixel.webp",
          "renaissance": "/niv/f066823c31c2/stylized-renaissance.webp",
          "anime": "/niv/f066823c31c2/stylized-anime.webp",
          "mugshot": "/niv/f066823c31c2/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "35a92b456083",
      "caption": "Niv eats one joint and considers himself a snake.",
      "tier": "bronze",
      "game": "snake-niv",
      "milestone": "snake:length:5",
      "paths": {
        "avatar64": "/niv/35a92b456083/avatar-64.webp",
        "avatar128": "/niv/35a92b456083/avatar-128.webp",
        "avatar256": "/niv/35a92b456083/avatar-256.webp",
        "portrait720": "/niv/35a92b456083/portrait-720.webp"
      }
    },
    {
      "slug": "a4ab87eb42bb",
      "caption": "Length 10. Niv has a personality now.",
      "tier": "bronze",
      "game": "snake-niv",
      "milestone": "snake:length:10",
      "paths": {
        "avatar64": "/niv/a4ab87eb42bb/avatar-64.webp",
        "avatar128": "/niv/a4ab87eb42bb/avatar-128.webp",
        "avatar256": "/niv/a4ab87eb42bb/avatar-256.webp",
        "portrait720": "/niv/a4ab87eb42bb/portrait-720.webp"
      }
    },
    {
      "slug": "a2506ec4ef89",
      "caption": "Length 25. The snake is beginning to ask questions.",
      "tier": "silver",
      "game": "snake-niv",
      "milestone": "snake:length:25",
      "paths": {
        "avatar64": "/niv/a2506ec4ef89/avatar-64.webp",
        "avatar128": "/niv/a2506ec4ef89/avatar-128.webp",
        "avatar256": "/niv/a2506ec4ef89/avatar-256.webp",
        "portrait720": "/niv/a2506ec4ef89/portrait-720.webp"
      }
    },
    {
      "slug": "d26c5062c1c9",
      "caption": "Length 50. Niv refuses corporate jobs on principle.",
      "tier": "silver",
      "game": "snake-niv",
      "milestone": "snake:length:50",
      "paths": {
        "avatar64": "/niv/d26c5062c1c9/avatar-64.webp",
        "avatar128": "/niv/d26c5062c1c9/avatar-128.webp",
        "avatar256": "/niv/d26c5062c1c9/avatar-256.webp",
        "portrait720": "/niv/d26c5062c1c9/portrait-720.webp"
      }
    },
    {
      "slug": "0ba9a8172e1a",
      "caption": "Length 100. Niv becomes the snake. The snake becomes Niv.",
      "tier": "gold",
      "game": "snake-niv",
      "milestone": "snake:length:100",
      "paths": {
        "avatar64": "/niv/0ba9a8172e1a/avatar-64.webp",
        "avatar128": "/niv/0ba9a8172e1a/avatar-128.webp",
        "avatar256": "/niv/0ba9a8172e1a/avatar-256.webp",
        "portrait720": "/niv/0ba9a8172e1a/portrait-720.webp"
      }
    },
    {
      "slug": "23fcd1fe955f",
      "caption": "Length 200. Niv has transcended digestion.",
      "tier": "platinum",
      "game": "snake-niv",
      "milestone": "snake:length:200",
      "paths": {
        "avatar64": "/niv/23fcd1fe955f/avatar-64.webp",
        "avatar128": "/niv/23fcd1fe955f/avatar-128.webp",
        "avatar256": "/niv/23fcd1fe955f/avatar-256.webp",
        "portrait720": "/niv/23fcd1fe955f/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/23fcd1fe955f/stylized-pixel.webp",
          "renaissance": "/niv/23fcd1fe955f/stylized-renaissance.webp",
          "anime": "/niv/23fcd1fe955f/stylized-anime.webp",
          "mugshot": "/niv/23fcd1fe955f/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "be8d20481d99",
      "caption": "First falafel. Authentic.",
      "tier": "bronze",
      "game": "snake-niv",
      "milestone": "snake:falafel:1",
      "paths": {
        "avatar64": "/niv/be8d20481d99/avatar-64.webp",
        "avatar128": "/niv/be8d20481d99/avatar-128.webp",
        "avatar256": "/niv/be8d20481d99/avatar-256.webp",
        "portrait720": "/niv/be8d20481d99/portrait-720.webp"
      }
    },
    {
      "slug": "10e44a121281",
      "caption": "Hummus tub annihilated. Hummus tub respected.",
      "tier": "silver",
      "game": "snake-niv",
      "milestone": "snake:hummus:1",
      "paths": {
        "avatar64": "/niv/10e44a121281/avatar-64.webp",
        "avatar128": "/niv/10e44a121281/avatar-128.webp",
        "avatar256": "/niv/10e44a121281/avatar-256.webp",
        "portrait720": "/niv/10e44a121281/portrait-720.webp"
      }
    },
    {
      "slug": "bc4017c80b58",
      "caption": "Self-bite at length 7. Niv discovers irony.",
      "tier": "bronze",
      "game": "snake-niv",
      "milestone": "snake:selfbite",
      "paths": {
        "avatar64": "/niv/bc4017c80b58/avatar-64.webp",
        "avatar128": "/niv/bc4017c80b58/avatar-128.webp",
        "avatar256": "/niv/bc4017c80b58/avatar-256.webp",
        "portrait720": "/niv/bc4017c80b58/portrait-720.webp"
      }
    },
    {
      "slug": "10f81ba7ce1a",
      "caption": "Wall hit at length 3. Niv was busy texting.",
      "tier": "bronze",
      "game": "snake-niv",
      "milestone": "snake:wall:short",
      "paths": {
        "avatar64": "/niv/10f81ba7ce1a/avatar-64.webp",
        "avatar128": "/niv/10f81ba7ce1a/avatar-128.webp",
        "avatar256": "/niv/10f81ba7ce1a/avatar-256.webp",
        "portrait720": "/niv/10f81ba7ce1a/portrait-720.webp"
      }
    },
    {
      "slug": "e5e9986004b5",
      "caption": "Score 500. Niv reads the rules of the game.",
      "tier": "silver",
      "game": "snake-niv",
      "milestone": "snake:score:500",
      "paths": {
        "avatar64": "/niv/e5e9986004b5/avatar-64.webp",
        "avatar128": "/niv/e5e9986004b5/avatar-128.webp",
        "avatar256": "/niv/e5e9986004b5/avatar-256.webp",
        "portrait720": "/niv/e5e9986004b5/portrait-720.webp"
      }
    },
    {
      "slug": "f15ff85ba8ae",
      "caption": "Score 1500. Niv is winning at something.",
      "tier": "gold",
      "game": "snake-niv",
      "milestone": "snake:score:1500",
      "paths": {
        "avatar64": "/niv/f15ff85ba8ae/avatar-64.webp",
        "avatar128": "/niv/f15ff85ba8ae/avatar-128.webp",
        "avatar256": "/niv/f15ff85ba8ae/avatar-256.webp",
        "portrait720": "/niv/f15ff85ba8ae/portrait-720.webp"
      }
    },
    {
      "slug": "56b229973f69",
      "caption": "Score 3000. Snake-Niv: Endgame.",
      "tier": "platinum",
      "game": "snake-niv",
      "milestone": "snake:score:3000",
      "paths": {
        "avatar64": "/niv/56b229973f69/avatar-64.webp",
        "avatar128": "/niv/56b229973f69/avatar-128.webp",
        "avatar256": "/niv/56b229973f69/avatar-256.webp",
        "portrait720": "/niv/56b229973f69/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/56b229973f69/stylized-pixel.webp",
          "renaissance": "/niv/56b229973f69/stylized-renaissance.webp",
          "anime": "/niv/56b229973f69/stylized-anime.webp",
          "mugshot": "/niv/56b229973f69/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "c7851bde44e7",
      "caption": "10 joints in 30 seconds. Niv has speedrun standards.",
      "tier": "gold",
      "game": "snake-niv",
      "milestone": "snake:burst:10in30",
      "paths": {
        "avatar64": "/niv/c7851bde44e7/avatar-64.webp",
        "avatar128": "/niv/c7851bde44e7/avatar-128.webp",
        "avatar256": "/niv/c7851bde44e7/avatar-256.webp",
        "portrait720": "/niv/c7851bde44e7/portrait-720.webp"
      }
    },
    {
      "slug": "359e184ac83f",
      "caption": "Survived 3 minutes. Niv missed three calls.",
      "tier": "silver",
      "game": "snake-niv",
      "milestone": "snake:time:180s",
      "paths": {
        "avatar64": "/niv/359e184ac83f/avatar-64.webp",
        "avatar128": "/niv/359e184ac83f/avatar-128.webp",
        "avatar256": "/niv/359e184ac83f/avatar-256.webp",
        "portrait720": "/niv/359e184ac83f/portrait-720.webp"
      }
    },
    {
      "slug": "60e5c388b6a1",
      "caption": "No-falafel run, length 30. Niv hates Yotam.",
      "tier": "gold",
      "game": "snake-niv",
      "milestone": "snake:nofalafel:30",
      "paths": {
        "avatar64": "/niv/60e5c388b6a1/avatar-64.webp",
        "avatar128": "/niv/60e5c388b6a1/avatar-128.webp",
        "avatar256": "/niv/60e5c388b6a1/avatar-256.webp",
        "portrait720": "/niv/60e5c388b6a1/portrait-720.webp"
      }
    },
    {
      "slug": "662b37f4c423",
      "caption": "All-falafel run, length 30. Niv loves Yotam.",
      "tier": "gold",
      "game": "snake-niv",
      "milestone": "snake:allfalafel:30",
      "paths": {
        "avatar64": "/niv/662b37f4c423/avatar-64.webp",
        "avatar128": "/niv/662b37f4c423/avatar-128.webp",
        "avatar256": "/niv/662b37f4c423/avatar-256.webp",
        "portrait720": "/niv/662b37f4c423/portrait-720.webp"
      }
    },
    {
      "slug": "f4fbc322b323",
      "caption": "First death. Welcome to Snake-Niv.",
      "tier": "bronze",
      "game": "snake-niv",
      "milestone": "snake:firstdeath",
      "paths": {
        "avatar64": "/niv/f4fbc322b323/avatar-64.webp",
        "avatar128": "/niv/f4fbc322b323/avatar-128.webp",
        "avatar256": "/niv/f4fbc322b323/avatar-256.webp",
        "portrait720": "/niv/f4fbc322b323/portrait-720.webp"
      }
    },
    {
      "slug": "967c3692efe1",
      "caption": "First match. Niv pretends he wasn't lucky.",
      "tier": "bronze",
      "game": "niv-memory",
      "milestone": "memory:match:1",
      "paths": {
        "avatar64": "/niv/967c3692efe1/avatar-64.webp",
        "avatar128": "/niv/967c3692efe1/avatar-128.webp",
        "avatar256": "/niv/967c3692efe1/avatar-256.webp",
        "portrait720": "/niv/967c3692efe1/portrait-720.webp"
      }
    },
    {
      "slug": "38675fe99f60",
      "caption": "5 matches. Niv claims he has photographic memory.",
      "tier": "bronze",
      "game": "niv-memory",
      "milestone": "memory:match:5",
      "paths": {
        "avatar64": "/niv/38675fe99f60/avatar-64.webp",
        "avatar128": "/niv/38675fe99f60/avatar-128.webp",
        "avatar256": "/niv/38675fe99f60/avatar-256.webp",
        "portrait720": "/niv/38675fe99f60/portrait-720.webp"
      }
    },
    {
      "slug": "ae52b7c7ebcf",
      "caption": "Easy board cleared. Niv has finished kindergarten.",
      "tier": "bronze",
      "game": "niv-memory",
      "milestone": "memory:clear:easy",
      "paths": {
        "avatar64": "/niv/ae52b7c7ebcf/avatar-64.webp",
        "avatar128": "/niv/ae52b7c7ebcf/avatar-128.webp",
        "avatar256": "/niv/ae52b7c7ebcf/avatar-256.webp",
        "portrait720": "/niv/ae52b7c7ebcf/portrait-720.webp"
      }
    },
    {
      "slug": "d01a2f49cfa8",
      "caption": "Medium board cleared. Niv has finished middle school.",
      "tier": "silver",
      "game": "niv-memory",
      "milestone": "memory:clear:medium",
      "paths": {
        "avatar64": "/niv/d01a2f49cfa8/avatar-64.webp",
        "avatar128": "/niv/d01a2f49cfa8/avatar-128.webp",
        "avatar256": "/niv/d01a2f49cfa8/avatar-256.webp",
        "portrait720": "/niv/d01a2f49cfa8/portrait-720.webp"
      }
    },
    {
      "slug": "12f0ab4ee669",
      "caption": "Hard board cleared. Niv has finished therapy.",
      "tier": "gold",
      "game": "niv-memory",
      "milestone": "memory:clear:hard",
      "paths": {
        "avatar64": "/niv/12f0ab4ee669/avatar-64.webp",
        "avatar128": "/niv/12f0ab4ee669/avatar-128.webp",
        "avatar256": "/niv/12f0ab4ee669/avatar-256.webp",
        "portrait720": "/niv/12f0ab4ee669/portrait-720.webp"
      }
    },
    {
      "slug": "d43ae3427e5b",
      "caption": "Hard board, sub-2-min. Niv was definitely cheating.",
      "tier": "platinum",
      "game": "niv-memory",
      "milestone": "memory:clear:hard:120s",
      "paths": {
        "avatar64": "/niv/d43ae3427e5b/avatar-64.webp",
        "avatar128": "/niv/d43ae3427e5b/avatar-128.webp",
        "avatar256": "/niv/d43ae3427e5b/avatar-256.webp",
        "portrait720": "/niv/d43ae3427e5b/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/d43ae3427e5b/stylized-pixel.webp",
          "renaissance": "/niv/d43ae3427e5b/stylized-renaissance.webp",
          "anime": "/niv/d43ae3427e5b/stylized-anime.webp",
          "mugshot": "/niv/d43ae3427e5b/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "6263fb5e852e",
      "caption": "10 mismatches in a row. Niv is going through it.",
      "tier": "bronze",
      "game": "niv-memory",
      "milestone": "memory:miss:10",
      "paths": {
        "avatar64": "/niv/6263fb5e852e/avatar-64.webp",
        "avatar128": "/niv/6263fb5e852e/avatar-128.webp",
        "avatar256": "/niv/6263fb5e852e/avatar-256.webp",
        "portrait720": "/niv/6263fb5e852e/portrait-720.webp"
      }
    },
    {
      "slug": "631b83e8f4c7",
      "caption": "Three matches in a row. Niv enters the zone.",
      "tier": "silver",
      "game": "niv-memory",
      "milestone": "memory:streak:3",
      "paths": {
        "avatar64": "/niv/631b83e8f4c7/avatar-64.webp",
        "avatar128": "/niv/631b83e8f4c7/avatar-128.webp",
        "avatar256": "/niv/631b83e8f4c7/avatar-256.webp",
        "portrait720": "/niv/631b83e8f4c7/portrait-720.webp"
      }
    },
    {
      "slug": "f2b8c20699ec",
      "caption": "Five matches in a row. Niv is broadcasting live.",
      "tier": "gold",
      "game": "niv-memory",
      "milestone": "memory:streak:5",
      "paths": {
        "avatar64": "/niv/f2b8c20699ec/avatar-64.webp",
        "avatar128": "/niv/f2b8c20699ec/avatar-128.webp",
        "avatar256": "/niv/f2b8c20699ec/avatar-256.webp",
        "portrait720": "/niv/f2b8c20699ec/portrait-720.webp"
      }
    },
    {
      "slug": "fa65b32ad23a",
      "caption": "Easy board, perfect game. Niv frames the receipt.",
      "tier": "gold",
      "game": "niv-memory",
      "milestone": "memory:perfect:easy",
      "paths": {
        "avatar64": "/niv/fa65b32ad23a/avatar-64.webp",
        "avatar128": "/niv/fa65b32ad23a/avatar-128.webp",
        "avatar256": "/niv/fa65b32ad23a/avatar-256.webp",
        "portrait720": "/niv/fa65b32ad23a/portrait-720.webp"
      }
    },
    {
      "slug": "23719882f3bb",
      "caption": "Medium board, perfect game. Niv calls his ex.",
      "tier": "gold",
      "game": "niv-memory",
      "milestone": "memory:perfect:medium",
      "paths": {
        "avatar64": "/niv/23719882f3bb/avatar-64.webp",
        "avatar128": "/niv/23719882f3bb/avatar-128.webp",
        "avatar256": "/niv/23719882f3bb/avatar-256.webp",
        "portrait720": "/niv/23719882f3bb/portrait-720.webp"
      }
    },
    {
      "slug": "f9e391346c4f",
      "caption": "Hard board, perfect game. Niv ascends.",
      "tier": "platinum",
      "game": "niv-memory",
      "milestone": "memory:perfect:hard",
      "paths": {
        "avatar64": "/niv/f9e391346c4f/avatar-64.webp",
        "avatar128": "/niv/f9e391346c4f/avatar-128.webp",
        "avatar256": "/niv/f9e391346c4f/avatar-256.webp",
        "portrait720": "/niv/f9e391346c4f/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/f9e391346c4f/stylized-pixel.webp",
          "renaissance": "/niv/f9e391346c4f/stylized-renaissance.webp",
          "anime": "/niv/f9e391346c4f/stylized-anime.webp",
          "mugshot": "/niv/f9e391346c4f/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "75487b35ee58",
      "caption": "Played 5 rounds. Niv has discovered repetition.",
      "tier": "silver",
      "game": "niv-memory",
      "milestone": "memory:rounds:5",
      "paths": {
        "avatar64": "/niv/75487b35ee58/avatar-64.webp",
        "avatar128": "/niv/75487b35ee58/avatar-128.webp",
        "avatar256": "/niv/75487b35ee58/avatar-256.webp",
        "portrait720": "/niv/75487b35ee58/portrait-720.webp"
      }
    },
    {
      "slug": "f1c589edfcb8",
      "caption": "Played 25 rounds. Niv lives here now.",
      "tier": "gold",
      "game": "niv-memory",
      "milestone": "memory:rounds:25",
      "paths": {
        "avatar64": "/niv/f1c589edfcb8/avatar-64.webp",
        "avatar128": "/niv/f1c589edfcb8/avatar-128.webp",
        "avatar256": "/niv/f1c589edfcb8/avatar-256.webp",
        "portrait720": "/niv/f1c589edfcb8/portrait-720.webp"
      }
    },
    {
      "slug": "f768299e2ce3",
      "caption": "First mismatch. Niv blames the screen.",
      "tier": "bronze",
      "game": "niv-memory",
      "milestone": "memory:firstmiss",
      "paths": {
        "avatar64": "/niv/f768299e2ce3/avatar-64.webp",
        "avatar128": "/niv/f768299e2ce3/avatar-128.webp",
        "avatar256": "/niv/f768299e2ce3/avatar-256.webp",
        "portrait720": "/niv/f768299e2ce3/portrait-720.webp"
      }
    },
    {
      "slug": "802cac484787",
      "caption": "Cleared a board in 15 moves flat.",
      "tier": "silver",
      "game": "niv-memory",
      "milestone": "memory:moves:15",
      "paths": {
        "avatar64": "/niv/802cac484787/avatar-64.webp",
        "avatar128": "/niv/802cac484787/avatar-128.webp",
        "avatar256": "/niv/802cac484787/avatar-256.webp",
        "portrait720": "/niv/802cac484787/portrait-720.webp"
      }
    },
    {
      "slug": "a76d8ca19331",
      "caption": "Cleared with the timer below 30s. Niv is a robot.",
      "tier": "platinum",
      "game": "niv-memory",
      "milestone": "memory:fast:30s",
      "paths": {
        "avatar64": "/niv/a76d8ca19331/avatar-64.webp",
        "avatar128": "/niv/a76d8ca19331/avatar-128.webp",
        "avatar256": "/niv/a76d8ca19331/avatar-256.webp",
        "portrait720": "/niv/a76d8ca19331/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/a76d8ca19331/stylized-pixel.webp",
          "renaissance": "/niv/a76d8ca19331/stylized-renaissance.webp",
          "anime": "/niv/a76d8ca19331/stylized-anime.webp",
          "mugshot": "/niv/a76d8ca19331/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "a5afc11f72da",
      "caption": "Quit mid-board. Niv had a thought.",
      "tier": "bronze",
      "game": "niv-memory",
      "milestone": "memory:quit",
      "paths": {
        "avatar64": "/niv/a5afc11f72da/avatar-64.webp",
        "avatar128": "/niv/a5afc11f72da/avatar-128.webp",
        "avatar256": "/niv/a5afc11f72da/avatar-256.webp",
        "portrait720": "/niv/a5afc11f72da/portrait-720.webp"
      }
    },
    {
      "slug": "7cab6e23dabf",
      "caption": "Beat Stoned Niv. Difficulty: was-already-asleep.",
      "tier": "bronze",
      "game": "niv-tac-toe",
      "milestone": "xo:win:stoned",
      "paths": {
        "avatar64": "/niv/7cab6e23dabf/avatar-64.webp",
        "avatar128": "/niv/7cab6e23dabf/avatar-128.webp",
        "avatar256": "/niv/7cab6e23dabf/avatar-256.webp",
        "portrait720": "/niv/7cab6e23dabf/portrait-720.webp"
      }
    },
    {
      "slug": "e261da3b2ce8",
      "caption": "Beat Sober Niv. Mathematically impossible. Show-off.",
      "tier": "platinum",
      "game": "niv-tac-toe",
      "milestone": "xo:win:sober",
      "paths": {
        "avatar64": "/niv/e261da3b2ce8/avatar-64.webp",
        "avatar128": "/niv/e261da3b2ce8/avatar-128.webp",
        "avatar256": "/niv/e261da3b2ce8/avatar-256.webp",
        "portrait720": "/niv/e261da3b2ce8/portrait-720.webp",
        "stylized": {
          "pixel": "/niv/e261da3b2ce8/stylized-pixel.webp",
          "renaissance": "/niv/e261da3b2ce8/stylized-renaissance.webp",
          "anime": "/niv/e261da3b2ce8/stylized-anime.webp",
          "mugshot": "/niv/e261da3b2ce8/stylized-mugshot.webp"
        }
      }
    },
    {
      "slug": "ec00d1804f38",
      "caption": "Drew Sober Niv. The honorable outcome.",
      "tier": "silver",
      "game": "niv-tac-toe",
      "milestone": "xo:draw:sober",
      "paths": {
        "avatar64": "/niv/ec00d1804f38/avatar-64.webp",
        "avatar128": "/niv/ec00d1804f38/avatar-128.webp",
        "avatar256": "/niv/ec00d1804f38/avatar-256.webp",
        "portrait720": "/niv/ec00d1804f38/portrait-720.webp"
      }
    },
    {
      "slug": "42222062da1c",
      "caption": "Lost to Stoned Niv. Take the L. Reflect.",
      "tier": "bronze",
      "game": "niv-tac-toe",
      "milestone": "xo:loss:stoned",
      "paths": {
        "avatar64": "/niv/42222062da1c/avatar-64.webp",
        "avatar128": "/niv/42222062da1c/avatar-128.webp",
        "avatar256": "/niv/42222062da1c/avatar-256.webp",
        "portrait720": "/niv/42222062da1c/portrait-720.webp"
      }
    },
    {
      "slug": "7aae14fcca1b",
      "caption": "5 wins in a row vs Stoned Niv.",
      "tier": "silver",
      "game": "niv-tac-toe",
      "milestone": "xo:streak:stoned:5",
      "paths": {
        "avatar64": "/niv/7aae14fcca1b/avatar-64.webp",
        "avatar128": "/niv/7aae14fcca1b/avatar-128.webp",
        "avatar256": "/niv/7aae14fcca1b/avatar-256.webp",
        "portrait720": "/niv/7aae14fcca1b/portrait-720.webp"
      }
    },
    {
      "slug": "791888fb3986",
      "caption": "10 wins in a row vs Stoned Niv. Niv is very proud.",
      "tier": "gold",
      "game": "niv-tac-toe",
      "milestone": "xo:streak:stoned:10",
      "paths": {
        "avatar64": "/niv/791888fb3986/avatar-64.webp",
        "avatar128": "/niv/791888fb3986/avatar-128.webp",
        "avatar256": "/niv/791888fb3986/avatar-256.webp",
        "portrait720": "/niv/791888fb3986/portrait-720.webp"
      }
    },
    {
      "slug": "d48208a6d9a1",
      "caption": "Won in 3 moves. Did Niv even try.",
      "tier": "silver",
      "game": "niv-tac-toe",
      "milestone": "xo:win:fast",
      "paths": {
        "avatar64": "/niv/d48208a6d9a1/avatar-64.webp",
        "avatar128": "/niv/d48208a6d9a1/avatar-128.webp",
        "avatar256": "/niv/d48208a6d9a1/avatar-256.webp",
        "portrait720": "/niv/d48208a6d9a1/portrait-720.webp"
      }
    },
    {
      "slug": "a5ca2f46b618",
      "caption": "Played 25 games. Niv has made friends with the AI.",
      "tier": "silver",
      "game": "niv-tac-toe",
      "milestone": "xo:played:25",
      "paths": {
        "avatar64": "/niv/a5ca2f46b618/avatar-64.webp",
        "avatar128": "/niv/a5ca2f46b618/avatar-128.webp",
        "avatar256": "/niv/a5ca2f46b618/avatar-256.webp",
        "portrait720": "/niv/a5ca2f46b618/portrait-720.webp"
      }
    },
    {
      "slug": "8e7e6bed4912",
      "caption": "Played 100 games. Therapy time.",
      "tier": "gold",
      "game": "niv-tac-toe",
      "milestone": "xo:played:100",
      "paths": {
        "avatar64": "/niv/8e7e6bed4912/avatar-64.webp",
        "avatar128": "/niv/8e7e6bed4912/avatar-128.webp",
        "avatar256": "/niv/8e7e6bed4912/avatar-256.webp",
        "portrait720": "/niv/8e7e6bed4912/portrait-720.webp"
      }
    },
    {
      "slug": "c76e2c8a13ed",
      "caption": "First game. Welcome to Niv-Tac-Toe.",
      "tier": "bronze",
      "game": "niv-tac-toe",
      "milestone": "xo:firstgame",
      "paths": {
        "avatar64": "/niv/c76e2c8a13ed/avatar-64.webp",
        "avatar128": "/niv/c76e2c8a13ed/avatar-128.webp",
        "avatar256": "/niv/c76e2c8a13ed/avatar-256.webp",
        "portrait720": "/niv/c76e2c8a13ed/portrait-720.webp"
      }
    },
    {
      "slug": "67a51f36377b",
      "caption": "Drew 3 in a row. Niv suspects the AI is bored.",
      "tier": "silver",
      "game": "niv-tac-toe",
      "milestone": "xo:draw:streak:3",
      "paths": {
        "avatar64": "/niv/67a51f36377b/avatar-64.webp",
        "avatar128": "/niv/67a51f36377b/avatar-128.webp",
        "avatar256": "/niv/67a51f36377b/avatar-256.webp",
        "portrait720": "/niv/67a51f36377b/portrait-720.webp"
      }
    },
    {
      "slug": "e63623980b73",
      "caption": "Win + draw + win pattern. Niv is unpredictable.",
      "tier": "gold",
      "game": "niv-tac-toe",
      "milestone": "xo:wdw",
      "paths": {
        "avatar64": "/niv/e63623980b73/avatar-64.webp",
        "avatar128": "/niv/e63623980b73/avatar-128.webp",
        "avatar256": "/niv/e63623980b73/avatar-256.webp",
        "portrait720": "/niv/e63623980b73/portrait-720.webp"
      }
    },
    {
      "slug": "7400b71e79b9",
      "caption": "First brick destroyed. 'Pay rent' is now bricks.",
      "tier": "bronze",
      "game": "brick-niv",
      "milestone": "brick:break:1",
      "paths": {
        "avatar64": "/niv/7400b71e79b9/avatar-64.webp",
        "avatar128": "/niv/7400b71e79b9/avatar-128.webp",
        "avatar256": "/niv/7400b71e79b9/avatar-256.webp",
        "portrait720": "/niv/7400b71e79b9/portrait-720.webp"
      }
    },
    {
      "slug": "bd7534bb118d",
      "caption": "First power-up. Niv has multi-balls now.",
      "tier": "silver",
      "game": "brick-niv",
      "milestone": "brick:powerup:1",
      "paths": {
        "avatar64": "/niv/bd7534bb118d/avatar-64.webp",
        "avatar128": "/niv/bd7534bb118d/avatar-128.webp",
        "avatar256": "/niv/bd7534bb118d/avatar-256.webp",
        "portrait720": "/niv/bd7534bb118d/portrait-720.webp"
      }
    },
    {
      "slug": "d374144706b6",
      "caption": "Cleared first level. Niv resigns from his job.",
      "tier": "silver",
      "game": "brick-niv",
      "milestone": "brick:level:1",
      "paths": {
        "avatar64": "/niv/d374144706b6/avatar-64.webp",
        "avatar128": "/niv/d374144706b6/avatar-128.webp",
        "avatar256": "/niv/d374144706b6/avatar-256.webp",
        "portrait720": "/niv/d374144706b6/portrait-720.webp"
      }
    },
    {
      "slug": "c16516e4c695",
      "caption": "Score 1000. Niv is canceled.",
      "tier": "silver",
      "game": "brick-niv",
      "milestone": "brick:score:1000",
      "paths": {
        "avatar64": "/niv/c16516e4c695/avatar-64.webp",
        "avatar128": "/niv/c16516e4c695/avatar-128.webp",
        "avatar256": "/niv/c16516e4c695/avatar-256.webp",
        "portrait720": "/niv/c16516e4c695/portrait-720.webp"
      }
    },
    {
      "slug": "ac1d1f4406ee",
      "caption": "Score 3000. Niv is feared in two cities.",
      "tier": "gold",
      "game": "brick-niv",
      "milestone": "brick:score:3000",
      "paths": {
        "avatar64": "/niv/ac1d1f4406ee/avatar-64.webp",
        "avatar128": "/niv/ac1d1f4406ee/avatar-128.webp",
        "avatar256": "/niv/ac1d1f4406ee/avatar-256.webp",
        "portrait720": "/niv/ac1d1f4406ee/portrait-720.webp"
      }
    },
    {
      "slug": "55082906c7c7",
      "caption": "Score 7500. Niv: master of irresponsibility.",
      "tier": "platinum",
      "game": "brick-niv",
      "milestone": "brick:score:7500",
      "paths": {
        "avatar64": "/niv/55082906c7c7/avatar-64.webp",
        "avatar128": "/niv/55082906c7c7/avatar-128.webp",
        "avatar256": "/niv/55082906c7c7/avatar-256.webp",
        "portrait720": "/niv/55082906c7c7/portrait-720.webp"
      }
    },
    {
      "slug": "f847d895a52a",
      "caption": "Lost ball in 4 seconds. Speedrun mode.",
      "tier": "bronze",
      "game": "brick-niv",
      "milestone": "brick:fastloss",
      "paths": {
        "avatar64": "/niv/f847d895a52a/avatar-64.webp",
        "avatar128": "/niv/f847d895a52a/avatar-128.webp",
        "avatar256": "/niv/f847d895a52a/avatar-256.webp",
        "portrait720": "/niv/f847d895a52a/portrait-720.webp"
      }
    },
    {
      "slug": "318d70bb7344",
      "caption": "10 bricks in 5 seconds. Combo unleashed.",
      "tier": "gold",
      "game": "brick-niv",
      "milestone": "brick:burst:10in5",
      "paths": {
        "avatar64": "/niv/318d70bb7344/avatar-64.webp",
        "avatar128": "/niv/318d70bb7344/avatar-128.webp",
        "avatar256": "/niv/318d70bb7344/avatar-256.webp",
        "portrait720": "/niv/318d70bb7344/portrait-720.webp"
      }
    },
    {
      "slug": "ea2fd2027fd2",
      "caption": "Smashed 'Pay rent'. Niv has standards.",
      "tier": "silver",
      "game": "brick-niv",
      "milestone": "brick:rent",
      "paths": {
        "avatar64": "/niv/ea2fd2027fd2/avatar-64.webp",
        "avatar128": "/niv/ea2fd2027fd2/avatar-128.webp",
        "avatar256": "/niv/ea2fd2027fd2/avatar-256.webp",
        "portrait720": "/niv/ea2fd2027fd2/portrait-720.webp"
      }
    },
    {
      "slug": "c9849712f009",
      "caption": "Smashed 'Reply to mom'. Niv has chosen violence.",
      "tier": "silver",
      "game": "brick-niv",
      "milestone": "brick:replymom",
      "paths": {
        "avatar64": "/niv/c9849712f009/avatar-64.webp",
        "avatar128": "/niv/c9849712f009/avatar-128.webp",
        "avatar256": "/niv/c9849712f009/avatar-256.webp",
        "portrait720": "/niv/c9849712f009/portrait-720.webp"
      }
    },
    {
      "slug": "e1db48a008c0",
      "caption": "Smashed 'Gym'. Niv is who he is.",
      "tier": "silver",
      "game": "brick-niv",
      "milestone": "brick:gym",
      "paths": {
        "avatar64": "/niv/e1db48a008c0/avatar-64.webp",
        "avatar128": "/niv/e1db48a008c0/avatar-128.webp",
        "avatar256": "/niv/e1db48a008c0/avatar-256.webp",
        "portrait720": "/niv/e1db48a008c0/portrait-720.webp"
      }
    },
    {
      "slug": "b6c1830e79ae",
      "caption": "Smashed 'Taxes'. The IRS sends regards.",
      "tier": "gold",
      "game": "brick-niv",
      "milestone": "brick:taxes",
      "paths": {
        "avatar64": "/niv/b6c1830e79ae/avatar-64.webp",
        "avatar128": "/niv/b6c1830e79ae/avatar-128.webp",
        "avatar256": "/niv/b6c1830e79ae/avatar-256.webp",
        "portrait720": "/niv/b6c1830e79ae/portrait-720.webp"
      }
    },
    {
      "slug": "e94464c47485",
      "caption": "All adulting bricks smashed in one game.",
      "tier": "platinum",
      "game": "brick-niv",
      "milestone": "brick:adultsweep",
      "paths": {
        "avatar64": "/niv/e94464c47485/avatar-64.webp",
        "avatar128": "/niv/e94464c47485/avatar-128.webp",
        "avatar256": "/niv/e94464c47485/avatar-256.webp",
        "portrait720": "/niv/e94464c47485/portrait-720.webp"
      }
    },
    {
      "slug": "a802a1d30f57",
      "caption": "Multi-ball survived 30 seconds. Hand of god.",
      "tier": "gold",
      "game": "brick-niv",
      "milestone": "brick:multi:30s",
      "paths": {
        "avatar64": "/niv/a802a1d30f57/avatar-64.webp",
        "avatar128": "/niv/a802a1d30f57/avatar-128.webp",
        "avatar256": "/niv/a802a1d30f57/avatar-256.webp",
        "portrait720": "/niv/a802a1d30f57/portrait-720.webp"
      }
    },
    {
      "slug": "d9f16c47ffb2",
      "caption": "Wide paddle + slow ball + multi-ball at once.",
      "tier": "platinum",
      "game": "brick-niv",
      "milestone": "brick:tristack",
      "paths": {
        "avatar64": "/niv/d9f16c47ffb2/avatar-64.webp",
        "avatar128": "/niv/d9f16c47ffb2/avatar-128.webp",
        "avatar256": "/niv/d9f16c47ffb2/avatar-256.webp",
        "portrait720": "/niv/d9f16c47ffb2/portrait-720.webp"
      }
    },
    {
      "slug": "1fc6c1b8f9b6",
      "caption": "First game. Niv lost the ball before reading rules.",
      "tier": "bronze",
      "game": "brick-niv",
      "milestone": "brick:firstgame",
      "paths": {
        "avatar64": "/niv/1fc6c1b8f9b6/avatar-64.webp",
        "avatar128": "/niv/1fc6c1b8f9b6/avatar-128.webp",
        "avatar256": "/niv/1fc6c1b8f9b6/avatar-256.webp",
        "portrait720": "/niv/1fc6c1b8f9b6/portrait-720.webp"
      }
    },
    {
      "slug": "360a1d4b20b0",
      "caption": "First whack. Niv felt that.",
      "tier": "bronze",
      "game": "whack-a-niv",
      "milestone": "whack:hit:1",
      "paths": {
        "avatar64": "/niv/360a1d4b20b0/avatar-64.webp",
        "avatar128": "/niv/360a1d4b20b0/avatar-128.webp",
        "avatar256": "/niv/360a1d4b20b0/avatar-256.webp",
        "portrait720": "/niv/360a1d4b20b0/portrait-720.webp"
      }
    },
    {
      "slug": "1fa76cfde4dd",
      "caption": "10 whacks. Niv enjoys this less than you do.",
      "tier": "bronze",
      "game": "whack-a-niv",
      "milestone": "whack:hit:10",
      "paths": {
        "avatar64": "/niv/1fa76cfde4dd/avatar-64.webp",
        "avatar128": "/niv/1fa76cfde4dd/avatar-128.webp",
        "avatar256": "/niv/1fa76cfde4dd/avatar-256.webp",
        "portrait720": "/niv/1fa76cfde4dd/portrait-720.webp"
      }
    },
    {
      "slug": "6d76a2ee9e20",
      "caption": "25 whacks. Niv is filing a report.",
      "tier": "silver",
      "game": "whack-a-niv",
      "milestone": "whack:hit:25",
      "paths": {
        "avatar64": "/niv/6d76a2ee9e20/avatar-64.webp",
        "avatar128": "/niv/6d76a2ee9e20/avatar-128.webp",
        "avatar256": "/niv/6d76a2ee9e20/avatar-256.webp",
        "portrait720": "/niv/6d76a2ee9e20/portrait-720.webp"
      }
    },
    {
      "slug": "1d3976962b43",
      "caption": "50 whacks in 30s. Carpal tunnel: unlocked.",
      "tier": "gold",
      "game": "whack-a-niv",
      "milestone": "whack:hit:50",
      "paths": {
        "avatar64": "/niv/1d3976962b43/avatar-64.webp",
        "avatar128": "/niv/1d3976962b43/avatar-128.webp",
        "avatar256": "/niv/1d3976962b43/avatar-256.webp",
        "portrait720": "/niv/1d3976962b43/portrait-720.webp"
      }
    },
    {
      "slug": "4e0db04712db",
      "caption": "75 whacks. Niv is calling his lawyer.",
      "tier": "platinum",
      "game": "whack-a-niv",
      "milestone": "whack:hit:75",
      "paths": {
        "avatar64": "/niv/4e0db04712db/avatar-64.webp",
        "avatar128": "/niv/4e0db04712db/avatar-128.webp",
        "avatar256": "/niv/4e0db04712db/avatar-256.webp",
        "portrait720": "/niv/4e0db04712db/portrait-720.webp"
      }
    },
    {
      "slug": "35d73a16bbda",
      "caption": "Missed first whack. Niv laughs.",
      "tier": "bronze",
      "game": "whack-a-niv",
      "milestone": "whack:firstmiss",
      "paths": {
        "avatar64": "/niv/35d73a16bbda/avatar-64.webp",
        "avatar128": "/niv/35d73a16bbda/avatar-128.webp",
        "avatar256": "/niv/35d73a16bbda/avatar-256.webp",
        "portrait720": "/niv/35d73a16bbda/portrait-720.webp"
      }
    },
    {
      "slug": "353cfd001cae",
      "caption": "5 misses in a row. Niv is invincible today.",
      "tier": "bronze",
      "game": "whack-a-niv",
      "milestone": "whack:miss:5",
      "paths": {
        "avatar64": "/niv/353cfd001cae/avatar-64.webp",
        "avatar128": "/niv/353cfd001cae/avatar-128.webp",
        "avatar256": "/niv/353cfd001cae/avatar-256.webp",
        "portrait720": "/niv/353cfd001cae/portrait-720.webp"
      }
    },
    {
      "slug": "4d85793936fd",
      "caption": "Combo x5. Niv flinches.",
      "tier": "silver",
      "game": "whack-a-niv",
      "milestone": "whack:combo:5",
      "paths": {
        "avatar64": "/niv/4d85793936fd/avatar-64.webp",
        "avatar128": "/niv/4d85793936fd/avatar-128.webp",
        "avatar256": "/niv/4d85793936fd/avatar-256.webp",
        "portrait720": "/niv/4d85793936fd/portrait-720.webp"
      }
    },
    {
      "slug": "95cf58f10e98",
      "caption": "Combo x10. Niv blocks your number.",
      "tier": "gold",
      "game": "whack-a-niv",
      "milestone": "whack:combo:10",
      "paths": {
        "avatar64": "/niv/95cf58f10e98/avatar-64.webp",
        "avatar128": "/niv/95cf58f10e98/avatar-128.webp",
        "avatar256": "/niv/95cf58f10e98/avatar-256.webp",
        "portrait720": "/niv/95cf58f10e98/portrait-720.webp"
      }
    },
    {
      "slug": "b3d4965a00e4",
      "caption": "Combo x20. Niv has summoned the IDF.",
      "tier": "platinum",
      "game": "whack-a-niv",
      "milestone": "whack:combo:20",
      "paths": {
        "avatar64": "/niv/b3d4965a00e4/avatar-64.webp",
        "avatar128": "/niv/b3d4965a00e4/avatar-128.webp",
        "avatar256": "/niv/b3d4965a00e4/avatar-256.webp",
        "portrait720": "/niv/b3d4965a00e4/portrait-720.webp"
      }
    },
    {
      "slug": "a972c11fa5d7",
      "caption": "0 whacks in 30s. Niv wins by attendance.",
      "tier": "bronze",
      "game": "whack-a-niv",
      "milestone": "whack:zerogame",
      "paths": {
        "avatar64": "/niv/a972c11fa5d7/avatar-64.webp",
        "avatar128": "/niv/a972c11fa5d7/avatar-128.webp",
        "avatar256": "/niv/a972c11fa5d7/avatar-256.webp",
        "portrait720": "/niv/a972c11fa5d7/portrait-720.webp"
      }
    },
    {
      "slug": "35a6d46cb0a0",
      "caption": "First perfect 5s window.",
      "tier": "silver",
      "game": "whack-a-niv",
      "milestone": "whack:perfect5s",
      "paths": {
        "avatar64": "/niv/35a6d46cb0a0/avatar-64.webp",
        "avatar128": "/niv/35a6d46cb0a0/avatar-128.webp",
        "avatar256": "/niv/35a6d46cb0a0/avatar-256.webp",
        "portrait720": "/niv/35a6d46cb0a0/portrait-720.webp"
      }
    },
    {
      "slug": "49745d1c438e",
      "caption": "Hit a Niv that didn't fully emerge. Pre-crime.",
      "tier": "gold",
      "game": "whack-a-niv",
      "milestone": "whack:precrime",
      "paths": {
        "avatar64": "/niv/49745d1c438e/avatar-64.webp",
        "avatar128": "/niv/49745d1c438e/avatar-128.webp",
        "avatar256": "/niv/49745d1c438e/avatar-256.webp",
        "portrait720": "/niv/49745d1c438e/portrait-720.webp"
      }
    },
    {
      "slug": "3666f0525750",
      "caption": "Played 10 rounds. Niv has filed restraining order.",
      "tier": "silver",
      "game": "whack-a-niv",
      "milestone": "whack:rounds:10",
      "paths": {
        "avatar64": "/niv/3666f0525750/avatar-64.webp",
        "avatar128": "/niv/3666f0525750/avatar-128.webp",
        "avatar256": "/niv/3666f0525750/avatar-256.webp",
        "portrait720": "/niv/3666f0525750/portrait-720.webp"
      }
    },
    {
      "slug": "48c07e6d6ce9",
      "caption": "Played 50 rounds. Niv has retreated to the desert.",
      "tier": "gold",
      "game": "whack-a-niv",
      "milestone": "whack:rounds:50",
      "paths": {
        "avatar64": "/niv/48c07e6d6ce9/avatar-64.webp",
        "avatar128": "/niv/48c07e6d6ce9/avatar-128.webp",
        "avatar256": "/niv/48c07e6d6ce9/avatar-256.webp",
        "portrait720": "/niv/48c07e6d6ce9/portrait-720.webp"
      }
    },
    {
      "slug": "71a917934075",
      "caption": "Final hit was a clean slap on Niv's bald spot.",
      "tier": "platinum",
      "game": "whack-a-niv",
      "milestone": "whack:finalhit",
      "paths": {
        "avatar64": "/niv/71a917934075/avatar-64.webp",
        "avatar128": "/niv/71a917934075/avatar-128.webp",
        "avatar256": "/niv/71a917934075/avatar-256.webp",
        "portrait720": "/niv/71a917934075/portrait-720.webp"
      }
    }
  ]
} as const;
