// AUTO-GENERATED by scripts/gen-videos.ts
export interface NivVideo {
  slug: string;
  src: string;
  role: string;
  caption: string;
}
export const NIV_VIDEOS = {
  "version": 1,
  "generatedAt": "2026-05-09T19:19:06.517Z",
  "videos": [
    {
      "slug": "dancing",
      "src": "/niv-videos/dancing.mp4",
      "role": "victory",
      "caption": "Niv has won. Niv must dance."
    },
    {
      "slug": "lottery",
      "src": "/niv-videos/lottery.mp4",
      "role": "highscore",
      "caption": "NEW HIGH SCORE"
    },
    {
      "slug": "crying",
      "src": "/niv-videos/crying.mp4",
      "role": "gameover",
      "caption": "Niv is sad you lost."
    },
    {
      "slug": "sideeye",
      "src": "/niv-videos/sideeye.mp4",
      "role": "idle",
      "caption": "Niv is judging you."
    },
    {
      "slug": "screaming",
      "src": "/niv-videos/screaming.mp4",
      "role": "gameover",
      "caption": "Niv objects."
    }
  ]
} as const;
