import { promises as fs } from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { createHash } from "node:crypto";
import { CAPTIONS } from "../lib/achievements/captions";
import type { NivManifest, NivAsset } from "../lib/niv-types";

const ROOT = path.resolve(__dirname, "..");
const SRC_DIR = path.join(ROOT, "niv_media");
const OUT_DIR = path.join(ROOT, "public/niv");
const MANIFEST_PATH = path.join(ROOT, "lib/niv-manifest.ts");

async function main() {
  let sources: string[];
  try {
    sources = (await fs.readdir(SRC_DIR))
      .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
      .sort();
  } catch {
    console.error(`Cannot read ${SRC_DIR}. niv_media/ missing?`);
    process.exit(1);
  }

  if (sources.length === 0) {
    console.error(`No source images in ${SRC_DIR}`);
    process.exit(1);
  }

  if (sources.length < CAPTIONS.length) {
    console.warn(
      `Only ${sources.length} photos for ${CAPTIONS.length} captions. Some captions will share assets.`
    );
  }

  await fs.mkdir(OUT_DIR, { recursive: true });

  // Pre-validate sources: keep only those sharp can read.
  const validSources: string[] = [];
  for (const f of sources) {
    try {
      const m = await sharp(path.join(SRC_DIR, f)).metadata();
      if (m.width && m.height) validSources.push(f);
    } catch {
      console.warn(`  skipping unreadable: ${f}`);
    }
  }
  if (validSources.length === 0) {
    console.error("No readable source images");
    process.exit(1);
  }
  console.log(`  ${validSources.length} valid sources of ${sources.length}`);

  const assets: NivAsset[] = [];

  for (let i = 0; i < CAPTIONS.length; i++) {
    const caption = CAPTIONS[i];
    const srcFile = validSources[i % validSources.length];
    const srcPath = path.join(SRC_DIR, srcFile);
    const slug = createHash("sha1")
      .update(`${caption.milestone}::${srcFile}`)
      .digest("hex")
      .slice(0, 12);
    const dirOut = path.join(OUT_DIR, slug);
    await fs.mkdir(dirOut, { recursive: true });

    try {
      const meta = await sharp(srcPath).metadata();
      const w = meta.width ?? 1024;
      const h = meta.height ?? 1024;
      const size = Math.min(w, h);
      const left = Math.max(0, Math.floor((w - size) / 2));
      const top = Math.max(0, Math.floor((h - size) / 4));

      await sharp(srcPath, { failOn: "none" })
        .extract({ left, top, width: size, height: size })
        .resize(256, 256)
        .toFormat("webp", { quality: 88 })
        .toFile(path.join(dirOut, "avatar-256.webp"));

      await sharp(srcPath, { failOn: "none" })
        .extract({ left, top, width: size, height: size })
        .resize(128, 128)
        .toFormat("webp", { quality: 88 })
        .toFile(path.join(dirOut, "avatar-128.webp"));

      await sharp(srcPath, { failOn: "none" })
        .extract({ left, top, width: size, height: size })
        .resize(64, 64)
        .toFormat("webp", { quality: 88 })
        .toFile(path.join(dirOut, "avatar-64.webp"));

      await sharp(srcPath, { failOn: "none" })
        .resize({ width: 720, height: 720, fit: "inside" })
        .toFormat("webp", { quality: 80 })
        .toFile(path.join(dirOut, "portrait-720.webp"));

      assets.push({
        slug,
        caption: caption.caption,
        tier: caption.tier,
        game: caption.game,
        milestone: caption.milestone,
        paths: {
          avatar64: `/niv/${slug}/avatar-64.webp`,
          avatar128: `/niv/${slug}/avatar-128.webp`,
          avatar256: `/niv/${slug}/avatar-256.webp`,
          portrait720: `/niv/${slug}/portrait-720.webp`,
        },
      });
    } catch (err) {
      console.warn(`  failed on ${srcFile} for ${caption.milestone}: ${(err as Error).message}`);
      continue;
    }

    if ((i + 1) % 10 === 0) console.log(`  processed ${i + 1}/${CAPTIONS.length}`);
  }

  const manifest: NivManifest = {
    version: 1,
    generatedAt: new Date().toISOString(),
    assets,
  };

  const tsContent = `// AUTO-GENERATED by scripts/prep-assets.ts. Do not edit by hand.
import type { NivManifest } from "./niv-types";
export const NIV_MANIFEST: NivManifest = ${JSON.stringify(manifest, null, 2)} as const;
`;
  await fs.writeFile(MANIFEST_PATH, tsContent, "utf8");
  console.log(`\nWrote ${assets.length} assets and manifest to ${MANIFEST_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
