/**
 * Re-reads lib/niv-manifest.ts, scans public/niv/<slug>/ for any
 * stylized-<style>.webp files that exist on disk, and rewrites the
 * manifest with a `stylized` map merged into each asset's `paths`.
 * All other fields (including `version`, `generatedAt`, ordering, and
 * non-stylized paths) are preserved exactly. Writes the manifest in one
 * atomic step to avoid racing with the parallel Veo subagent.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { NIV_MANIFEST } from "../lib/niv-manifest";
import type { NivAsset, NivManifest } from "../lib/niv-types";

const ROOT = path.resolve(__dirname, "..");
const PUBLIC_DIR = path.join(ROOT, "public");
const MANIFEST_PATH = path.join(ROOT, "lib/niv-manifest.ts");

const KNOWN_STYLES = ["pixel", "renaissance", "anime", "mona", "mugshot"] as const;
type Style = (typeof KNOWN_STYLES)[number];

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function discoverStylized(slug: string): Promise<Partial<Record<Style, string>>> {
  const out: Partial<Record<Style, string>> = {};
  const slugDir = path.join(PUBLIC_DIR, "niv", slug);
  for (const style of KNOWN_STYLES) {
    const fname = `stylized-${style}.webp`;
    if (await fileExists(path.join(slugDir, fname))) {
      out[style] = `/niv/${slug}/${fname}`;
    }
  }
  return out;
}

function serialize(manifest: NivManifest): string {
  const header =
    "// AUTO-GENERATED by scripts/prep-assets.ts. Do not edit by hand.\n" +
    'import type { NivManifest } from "./niv-types";\n' +
    "export const NIV_MANIFEST: NivManifest = ";
  const body = JSON.stringify(manifest, null, 2);
  return `${header}${body} as const;\n`;
}

async function main() {
  const updated: NivAsset[] = [];
  let touched = 0;

  for (const asset of NIV_MANIFEST.assets) {
    const stylized = await discoverStylized(asset.slug);
    const hasAny = Object.keys(stylized).length > 0;
    if (hasAny) {
      // Merge with any pre-existing stylized map (preserve unknown keys).
      const merged = { ...(asset.paths.stylized ?? {}), ...stylized };
      updated.push({
        ...asset,
        paths: {
          ...asset.paths,
          stylized: merged,
        },
      });
      touched += 1;
    } else {
      // Preserve as-is.
      updated.push(asset);
    }
  }

  const next: NivManifest = {
    ...NIV_MANIFEST,
    assets: updated,
  };

  // Atomic write: write to a tmp file then rename. Reduces the risk of
  // a parallel writer (the Veo agent) seeing a half-written file.
  const tmp = `${MANIFEST_PATH}.tmp-stylized`;
  await fs.writeFile(tmp, serialize(next), "utf8");
  await fs.rename(tmp, MANIFEST_PATH);

  console.log(
    `Updated ${MANIFEST_PATH}: ${touched}/${NIV_MANIFEST.assets.length} assets carry stylized variants.`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
